"""Initial migration

Revision ID: 001689dcb07d
Revises:
Create Date: 2025-09-23 06:35:37.160222

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "001689dcb07d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
