"""Add is_active column to stocks table

Revision ID: 3a47b69bdd64
Revises: 001689dcb07d
Create Date: 2025-09-26 03:45:14.743851

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3a47b69bdd64"
down_revision = "001689dcb07d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stocks",
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default="true",
            nullable=False,
            comment="是否啟用",
        ),
    )
    op.create_index(op.f("ix_stocks_is_active"), "stocks", ["is_active"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stocks_is_active"), table_name="stocks")
    op.drop_column("stocks", "is_active")
    # ### end Alembic commands ###
